name: utmstore
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
#  sdk: ^3.7.2
#-----------------------PAKAGES---------------------------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  url_launcher: ^6.1.11
  intl: ^0.20.2
  logger: ^2.1.0
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
#  geolocation: ^11.0.0
  geolocator: ^14.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  # Product Specific

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_native_splash:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/logos/utmstore-logo-black.png
    image_dark: assets/logos/utmstore-logo-white.png
    android_12:
      color: "#FFFFFF"
      color_dark: "#000000"
      image: assets/logos/utmstore-logo-black.png
      image_dark: assets/logos/utmstore-logo-white.png
    web: false
flutter:
  uses-material-design: true

  #-------------------LOCAL ASSETS------------------------------------------
  assets:
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/on_boarding_images/
    - assets/images/content/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/logos/

  #-------------------LOCAL FONTS------------------------------------------
  fonts:
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf 
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family:    Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
        - asset: assets/fonts/coolvetica_regular_italic.otf
          style: italic

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
